### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by drclohite** [ReactTraining/react-router-5-course#10]
./src/styles/main.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js!./src/styles/main.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- C:\Users\Multiple Monitors\esorma\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\sass-loader\lib\loader.js
- C:\Users\Multiple Monitors\ESORMA\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\loader-runner\lib\loadLoader.js
- C:\Users\Multiple Monitors\ESORMA\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\loader-runner\lib\LoaderRunner.js
- C:\Users\Multiple Monitors\ESORMA\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\webpack\lib\NormalModule.js
- C:\Users\Multiple Monitors\ESORMA\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\webpack\lib\NormalModuleFactory.js
- C:\Users\Multiple Monitors\ESORMA\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\webpack\lib\Compiler.js
- C:\Users\Multiple Monitors\ESORMA\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\webpack\lib\webpack.js
- C:\Users\Multiple Monitors\ESORMA\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\webpack-dev-server\bin\webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.sassLoader (C:\Users\Multiple Monitors\esorma\routerCourse\react-router-5-course-master\react-router-5-course-master\node_modules\sass-loader\lib\loader.js:46:72)

**Comment by drclohite** [comment]
I then installed node-sass and got other errors.

**Comment by drclohite** [comment]
I upgraded node to the very latest version and it worked.
