### ISSUE TITLE
can't get branch 06-basics to build

### ISSUE THREAD

**Issue by anthonybrown** [ReactTraining/react-router-5-course#16]
Not sure what you need to debug?
I'm using node v12.20 (I figured it might work with a lower version of node?) I have all the branches, in fact, I had to do an `npm install node-sass -D` to get one other branch to work. Here's what the terminal shows after `npm start`
ERROR in ./src/wireframe/wireframes.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/lib/loader.js!./src/wireframe/wireframes.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'
Require stack:
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/sass-loader/lib/loader.js
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/loader-runner/lib/loadLoader.js
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/webpack/lib/NormalModule.js
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/webpack/lib/Compiler.js
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/webpack/lib/webpack.js
- /Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.sassLoader (/Users/tony/Documents/Development/ReactTraining/react-router-5-course/node_modules/sass-loader/lib/loader.js:46:72)
 @ ./src/wireframe/wireframes.scss 2:14-131
 @ ./src/wireframe/App.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 ./config/setup.js ./src/index.js
ℹ ｢wdm｣: Failed to compile.

**Comment by anthonybrown** [comment]
Here's what the browser shows
![Screen Shot 2020-12-06 at 5 39 07 PM](https://user-images.githubusercontent.com/1719818/101295179-0cb51100-37ea-11eb-953f-96205ddfdb92.png)

**Comment by anthonybrown** [comment]
I did another `npm i node-sass -D` and created a NotFound component and it built but I'm not sure if that's a fix?
